# Generated by Django 5.2.4 on 2025-08-01 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('repository_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GitPushEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pusher', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=255)),
                ('pushed_at', models.DateTimeField(auto_now_add=True)),
                ('commit_count', models.IntegerField()),
                ('raw_payload', models.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.gitproject')),
            ],
        ),
    ]
