# Generated by Django 5.2.4 on 2025-08-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_gitproject_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitproject',
            name='last_deploy',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gitproject',
            name='new_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gitproject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gitproject',
            name='webhook_secret',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
