# Generated by Django 5.2.4 on 2025-08-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_gitproject_last_deploy_gitproject_new_push_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitproject',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='gitproject',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gitproject',
            name='repository_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='gitproject',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
